languages = {}

languages["Deutsch"] =
{
    "AG": "AT",
    "Add": "Hinzufügen",
    "Away goals": "Auswärtstore",
    "Change in position": "Platzänderung",
    "D": "U",
    "For a draw": "Für ein Unentschieden",
    "For a loss": "Für eine Niederlage",
    "For a win": "Für einen Sieg",
    "GA": "TQ",
    "GD": "TD",
    "Generate league schedule": "Spielplan erzeugen",
    "Generates league schedules and tables for football (soccer) tournaments.": "Erzeugt Spielpläne und Tabellen für Fußballturniere.",
    "Goal average": "Torquotient",
    "Goal difference": "Tordifferenz",
    "Goals": "Tore",
    "Head-to-head comparison": "Direkter Vergleich",
    "Head-to-head criteria": "Kriterien im direkten Vergleich",
    "Help": "Hilfe",
    "L": "V",
    "Matchday": "Spieltag",
    "Matches drawn": "Unentschieden",
    "Matches lost": "Niederlagen",
    "Matches played": "Spiele",
    "Matches won": "Siege",
    "New": "Neu",
    "New league schedule": "Neuer Spielplan",
    "Number of rounds": "Anzahl Runden",
    "Open": "Öffnen",
    "Open league schedule": "Spielplan öffnen",
    "Pld": "Sp",
    "Points": "Punkte",
    "Pos": "Plz",
    "Pts": "Pkt",
    "Remove": "Entfernen",
    "Save": "Speichern",
    "Settings": "Einstellungen",
    "Table": "Tabelle",
    "Table statistics": "Tabellenstatistiken",
    "Team": "Mannschaft",
    "Teams": "Mannschaften",
    "Tiebreaker criteria": "Tabellenkriterien",
    "W": "G",
}

languages["English"] =
{
    "AG": "AG",
    "Add": "Add",
    "Away goals": "Away goals",
    "Change in position": "Change in position",
    "D": "D",
    "For a draw": "For a draw",
    "For a loss": "For a loss",
    "For a win": "For a win",
    "GA": "GA",
    "GD": "GD",
    "Generate league schedule": "Generate league schedule",
    "Generates league schedules and tables for football (soccer) tournaments.": "Generates league schedules and tables for football (soccer) tournaments.",
    "Goal average": "Goal average",
    "Goal difference": "Goal difference",
    "Goals": "Goals",
    "Head-to-head comparison": "Head-to-head comparison",
    "Head-to-head criteria": "Head-to-head criteria",
    "Help": "Help",
    "L": "L",
    "Matchday": "Matchday",
    "Matches drawn": "Matches drawn",
    "Matches lost": "Matches lost",
    "Matches played": "Matches played",
    "Matches won": "Matches won",
    "New": "New",
    "New league schedule": "New league schedule",
    "Number of rounds": "Number of rounds",
    "Open": "Open",
    "Open league schedule": "Open league schedule",
    "Pld": "Pld",
    "Points": "Points",
    "Pos": "Pos",
    "Pts": "Pts",
    "Remove": "Remove",
    "Save": "Save",
    "Settings": "Settings",
    "Table": "Table",
    "Table statistics": "Table statistics",
    "Team": "Team",
    "Teams": "Teams",
    "Tiebreaker criteria": "Tiebreaker criteria",
    "W": "W",
}

language = languages["English"]
